const CANVAS_WIDTH = 720;
const CANVAS_HEIGHT = 480;
const INITIAL_INDEX_COLOR = 0;
const MIN_BRUSH_WIDTH = 1;
const MAX_BRUSH_WIDTH = 25;
const STEP_BRUSH_WIDTH = 1;
const INITIAL_BRUSH_WIDTH = 5;
const COLORS = ["#f00", "#0f0", "#00f", "#ff0", "#f0f", "#0ff"];

export {
  CANVAS_HEIGHT,
  CANVAS_WIDTH,
  INITIAL_INDEX_COLOR,
  MIN_BRUSH_WIDTH,
  MAX_BRUSH_WIDTH,
  STEP_BRUSH_WIDTH,
  INITIAL_BRUSH_WIDTH,
  COLORS,
};
